.PHONY: clean All

All:
	@echo "----------Building project:[ finalproject - Debug ]----------"
	@cd "finalproject" && "$(MAKE)" -f  "finalproject.mk"
clean:
	@echo "----------Cleaning project:[ finalproject - Debug ]----------"
	@cd "finalproject" && "$(MAKE)" -f  "finalproject.mk" clean
